version: '2.1'

services:
 mssql:
  build:
    context: ./
    dockerfile: ./mssql/Dockerfile
    args:
      DB_PREFIX: ${SQL_DB_PREFIX}
  environment:
    ACCEPT_EULA: "Y"      
    SA_PASSWORD: ${SQL_SA_PASSWORD}
  mem_limit: 6048m
  networks:
    app_net:
      ipv4_address: 172.16.238.11  

 solr:
  build:
    context: ./
    dockerfile: ./solr/Dockerfile
    args:
      HOST_NAME: ${SOLR_HOST_NAME}
      PORT: ${SOLR_PORT}  
      SERVICE_NAME: ${SOLR_SERVICE_NAME}  
      XCONNECT_CORE_PREFIX: ${XCONNECT_SOLR_CORE_PREFIX}
      SITECORE_CORE_PREFIX: ${SITECORE_SOLR_CORE_PREFIX}
  ports:
    - ${SOLR_PORT}
  mem_limit: 4024m
  networks:
    app_net:
      ipv4_address: 172.16.238.10

 xconnect:
  build: 
    context: ./
    dockerfile: ./xconnect/Dockerfile
    args:
      SQL_SA_PASSWORD: ${SQL_SA_PASSWORD}
      SQL_DB_PREFIX: ${SQL_DB_PREFIX}
      SITE_NAME: ${XCONNECT_SITE_NAME}
      SOLR_CORE_PREFIX: ${XCONNECT_SOLR_CORE_PREFIX}
      SOLR_PORT: ${SOLR_PORT}
  volumes:
    - .\logs\xconnect:C:\inetpub\wwwroot\xconnect\App_data\Logs
  networks:
    app_net:
      ipv4_address: 172.16.238.12    
  depends_on:
    - mssql
    - solr

 sitecore:
  build: 
    context: ./
    dockerfile: ./sitecore/Dockerfile
    args:
      SQL_SA_PASSWORD: ${SQL_SA_PASSWORD}
      SQL_DB_PREFIX: ${SQL_DB_PREFIX}
      SITE_NAME: ${SITECORE_SITE_NAME}
      SOLR_PORT: ${SOLR_PORT}    
  volumes:
    - .\logs\sitecore:c:\inetpub\wwwroot\${SITECORE_SITE_NAME}\App_Data\logs
  depends_on:
    - xconnect
    - mssql
    - solr
  networks:
    app_net:
      ipv4_address: 172.16.238.13    

networks:
  app_net:
    ipam:
      driver: default
      config:
        -
          subnet: 172.16.238.0/24
          gateway: 172.16.238.1